### ISSUE TITLE
no `Hwbp` in the root

### ISSUE THREAD

**Issue by dr0pd34d** [3db6cd7f-e24c-4b34-917a-c79bc2c4c6cc/hwbp-rs#2]
Thank you for the project, I am currently trying to use it with Rust 1.63.0 and I get the following error:

```
unresolved imports `hwbp::Hwbp`, `hwbp::Index`, `hwbp::Size`, `hwbp::Condition`
no `Hwbp` in the root
```
This is for the following snippet:
```
use hwbp::{Hwbp, Index, Size, Condition};

fn main() {
    unsafe {
       let test = Hwbp::first();
    }
}
```

I cloned it locally and added it to my Cargo file.
I tried the provided examples, but somehow the "use" cannot find the types in the module root.
Is this because of the module being written for an older version of Rust?

If not, what am I possibly missing?

**Comment by wildbook** [comment]
Your snippet works fine for me, using this `Cargo.toml`:
```toml
[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
hwbp = { git = "https://github.com/wildbook/hwbp-rs" }
```

I'm not sure why you're running into issues, but all of those should be exported from this crate. 

The only reasonable guess I have is that you're referencing the wrong crate in your `Cargo.toml`, so check if that's it.
